title = "Hokkaido Univ Bioinformatics"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "ja"
languageName = "Japanese"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "Ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.Ja]
    title = "北海道大学医学部 Bioinfo研究会"
    weight = 1
    contentDir = "content/ja"
  [languages.En]
    title = "Hokkaido Univ school of medicine Bioinformatics study group"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[cascade]
  featured_image = "/images/jj-ying-8bghKxNU1j0-unsplash.jpg"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "x"
url = "https://x.com/hokudaiBioinfo"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/HU-bioinfo"
