title = "北海道大学医学部 Bioinfo研究会"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "ja"
languageName = "Japanese"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.ja]
    title = "北海道大学医学部 Bioinfo研究会"
    weight = 1
    contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
[[menu.main]]
  name = "About Us"
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "Members"
  identifier = "members"
  url = "/members/"

[[menu.main]]
name = "Articles"
identifier = "articles"
url = "/articles/"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "x"
url = "https://x.com/hokudaiBioinfo"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/HU-bioinfo"
