# theme = 'ananke'
theme = "github.com/alex-shpak/hugo-book"
title = "北海道大学医学部 Bioinfo研究会"
baseURL = "https://hu-bioinfo.github.io"
languageCode = "ja"
languageName = "Japanese"
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "../resources"
publishDir = "docs"
canonifyurls = true

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[languages]
  [languages.ja]
    title = "北海道大学医学部 Bioinfo研究会"
    weight = 1
    contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
[[menu.before]]
  name = "About"
  url = "/docs/about/"
  weight = 10

[[menu.after]]
  name = "Github"
  url = "https://github.com/alex-shpak/hugo-book"
  weight = 10

[[menu.after]]
  name = "Hugo Themes"
  url = "https://themes.gohugo.io/themes/hugo-book/"
  weight = 20

[[menu.main]]
  name = "About Us"
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "Members"
  identifier = "members"
  url = "/members/"

[[menu.main]]
  name = "Articles"
  identifier = "articles"
  url = "/articles/"

[params]
  BookTheme = 'auto'
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
  name = "x"
  url = "https://x.com/hokudaiBioinfo"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/HU-bioinfo"
