theme = "github.com/alex-shpak/hugo-book"
title = "北海道大学医学部 Bioinfo研究会"
baseURL = "https://hu-bioinfo.github.io"
languageCode = "ja"
languageName = "Japanese"
canonifyurls = true

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
enableRobotsTXT = false

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[languages]
  [languages.ja]
    title = "北海道大学医学部 Bioinfo研究会"
    weight = 1
    contentDir = "content"

[menu]
[[menu.after]]
  name = "Github"
  url = "https://github.com/HU-bioinfo/"
  weight = 10

[[menu.after]]
  name = "X"
  url = "https://x.com/hokudaiBioinfo"

[markup.goldmark.renderer]
  unsafe = true
