theme = "github.com/alex-shpak/hugo-book"
title = "北海道大学医学部 Bioinfo研究会"
baseURL = "https://hu-bioinfo.github.io"
languageCode = "ja"
languageName = "Japanese"
resourceDir = "../resources"
canonifyurls = true

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
enableRobotsTXT = true

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[languages]
  [languages.ja]
    title = "北海道大学医学部 Bioinfo研究会"
    weight = 1
    contentDir = "content"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
[[menu.before]]
  name = "About"
  url = "/docs/about/"
  weight = 10

[[menu.before]]
  name = "Members"
  url = "/docs/members/"
  weight = 10

[[menu.after]]
  name = "Github"
  url = "https://github.com/HU-bioinfo/"
  weight = 10

[[menu.after]]
  name = "X"
  url = "https://x.com/home"
