# theme = "github.com/HU-bioinfo/hugo-book" # Hugo Modulesを使用しているためコメントアウト
title = "北海道大学医学部 Bioinfo研究会"
baseURL = "https://hu-bioinfo.github.io"
languageCode = "ja"
languageName = "Japanese"
canonifyurls = false

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
enableRobotsTXT = false

summaryLength = 1

[module]
[[module.imports]]
path = 'github.com/HU-bioinfo/hugo-book'

[languages]
  [languages.ja]
    title = "北海道大学医学部 Bioinfo研究会"
    weight = 1
    contentDir = "content"

[menu]
[[menu.after]]
  name = "Github"
  url = "https://github.com/HU-bioinfo/"
  weight = 10

[[menu.after]]
  name = "X"
  url = "https://x.com/hokudaiBioinfo"

[params]
  BookMermaid = true

[markup.goldmark.renderer]
  unsafe = true
